run_on_device "$gpu_id" env TASK_NAME=index_add "$PYTHON_BIN" main.py \
    --path "$IDENTITY_OUTPUT_DIR" \
    --member_recovery_jsonl "$ONE_SHOT_OUTPUT_JSONL" \
    --output_filename "$INDEX_FILENAME" \
    --enable_emotion "$INDEX_ENABLE_EMOTION" \
    --enable_emotion_vlm "$INDEX_ENABLE_EMOTION_VLM" \
    --enable_body_pose "$INDEX_ENABLE_BODY_POSE" \
    --body_pose_detector "$INDEX_BODY_POSE_DETECTOR" \
    --body_pose_device "$DEVICE_ARG" \
    --emotion_vlm_device "$DEVICE_ARG" \
    --update_features mask_hole_quality face_boundary_quality \
    --mask_hole_threshold 5 \
    --quality_update_overwrite False \
    --enable_face_bbox_boundary_quality_check True \
    --enable_face_mask_coverage_quality_check True \
    --face_mask_min_foreground_ratio 0.90 \
    --face_quality_model_name buffalo_l \
    --face_quality_model_root /data/huanan/code/jwx1520881/HUAWEI_CrossPairDataset/pretrained_models/insightface \
    --face_quality_device cuda:0 \
    --face_quality_recompute_bbox False \
    --face_mask_coverage_max_abs_yaw 30.0 \
    --overwrite "$INDEX_OVERWRITE" \
    --rank "$g" \
    --total_rank "$NUM_P"
